### ISSUE TITLE
Getting error - Not able to load main class in maven:3.5.4-jdk-8

### ISSUE THREAD

**Issue by chinmay90kulkarni** [carlossg/docker-maven#92] opened 2018-10-30 08:23 UTC
After official update, **maven:3.5.4-jdk-8** throwing error in mvn package. Not able to load main class. Please check it. 

**Downgrading maven:3.5.4-jdk-8 to maven:3.5.3-jdk-8 solves the issue.**

![f33a4f5](https://user-images.githubusercontent.com/17756756/47704889-1226f100-dc4b-11e8-8a43-23e0dc3a33e6.png)

**Comment by ChristianStornowski** [comment] 2018-10-30 09:47
Same problem via gitlab with `image: maven:latest`.

**Comment by mdanielsson** [comment] 2018-10-30 09:48
The reason seems to be a broken openjdk package: 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925

**Comment by benjefferies** [comment] 2018-10-30 11:03
I was getting the issue with `maven:latest` but it went away when using `maven:3.5.4-jdk-8-alpine`. Not sure if this was fluke with cache but might be worth a try

**Comment by nicolasverle** [comment] 2018-10-30 11:07
> I was getting the issue with `maven:latest` but it went away when using `maven:3.5.4-jdk-8-alpine`. Not sure if this was fluke with cache but might be worth a try

Thanks but we use some libs in our build that are not Alpine compliant unfortunately :-(

**Comment by Noxaro** [comment] 2018-10-30 11:12
As temporary workaround the tag 3.5.3-jdk8 works for me.

**Comment by carlossg** [comment] 2018-10-30 11:35
> A quick fix would be greatly appreciated :-)

Always use SHA1 if you want reproducible builds

**Comment by Salokyn** [comment] 2018-10-30 14:00
We switched back to the previous image version maven@sha256:b37da91062d450f3c11c619187f0207bbb497fc89d265a46bbc6dc5f17c02a2b to fix this.
Created 2018-10-16T17:18:05.864810296Z.

**Comment by nicolasverle** [comment] 2018-10-30 15:59
> We switched back to the previous image version maven@sha256:b37da91062d450f3c11c619187f0207bbb497fc89d265a46bbc6dc5f17c02a2b to fix this.
> Created 2018-10-16T17:18:05.864810296Z.

That's a complete and wise answer.
Thanks a lot Salokyn.

**Comment by chinmay90kulkarni** [comment] 2018-10-30 17:00
> As temporary workaround the tag 3.5.3-jdk8 works for me.

Did the same thing as workaround!

**Comment by ibnesayeed** [comment] 2018-11-04 23:52
Having a broken `latest` tag for long is really not good for an official image. We can perhaps offset the base image in the interim to a specific hash when JDK 8 was not broken.

**Comment by carlossg** [comment] 2018-11-08 22:28
Docker official images get updated when there are upstream changes. There were updates to base Debian image

**Comment by jglick** [comment] 2018-11-30 15:08
Please close as a duplicate of #90.

**Closed** 2018-11-30 15:12 UTC
